MT.cpp File Reference
Mersenne Twister random number generator.
Defines
#define N 624
#define M 397
#define MATRIX_A 0x9908b0dfUL
#define UPPER_MASK 0x80000000UL
#define LOWER_MASK 0x7fffffffUL
Functions
void init_genrand (unsigned long s)
void init_by_array (unsigned long init_key[], int key_length)
unsigned long genrand_int32 (void)
long genrand_int31 (void)
double genrand_real1 (void)
double genrand_real2 (void)
double genrand_real3 (void)
double genrand_res53 (void)
Detailed Description
Mersenne Twister random number generator.
Definition in file MT.cpp.
Define Documentation
#define LOWER_MASK 0x7fffffffUL
Definition at line 55 of file MT.cpp.
Referenced by genrand_int32().
#define M 397
Definition at line 52 of file MT.cpp.
Referenced by genrand_int32().
#define MATRIX_A 0x9908b0dfUL
Definition at line 53 of file MT.cpp.
Referenced by genrand_int32().
#define N 624
Definition at line 51 of file MT.cpp.
Referenced by genrand_int32(), init_by_array(), init_genrand(), one_run(), and variation().
#define UPPER_MASK 0x80000000UL
Definition at line 54 of file MT.cpp.
Referenced by genrand_int32().
Function Documentation
long genrand_int31 (void)
Definition at line 144 of file MT.cpp.
References genrand_int32().
145 {
146     return (long)(genrand_int32()>>1);
147 }
unsigned long genrand_int32 (void)
Definition at line 106 of file MT.cpp.
References init_genrand(), LOWER_MASK, M, MATRIX_A, N, and UPPER_MASK.
Referenced by genrand_int31(), genrand_real1(), genrand_real2(), genrand_real3(), and genrand_res53().
107 {
108     unsigned long y;
109     static unsigned long mag01[2]={0x0UL, MATRIX_A};
110     /* mag01[x] = x * MATRIX_A  for x=0,1 */
111 
112     if (mti >= N) { /* generate N words at one time */
113         int kk;
114 
115         if (mti == N+1)   /* if init_genrand() has not been called, */
116             init_genrand(5489UL); /* a default initial seed is used */
117 
118         for (kk=0;kk<N-M;kk++) {
119             y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
120             mt[kk] = mt[kk+M] ^ (y >> 1) ^ mag01[y & 0x1UL];
121         }
122         for (;kk<N-1;kk++) {
123             y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
124             mt[kk] = mt[kk+(M-N)] ^ (y >> 1) ^ mag01[y & 0x1UL];
125         }
126         y = (mt[N-1]&UPPER_MASK)|(mt[0]&LOWER_MASK);
127         mt[N-1] = mt[M-1] ^ (y >> 1) ^ mag01[y & 0x1UL];
128 
129         mti = 0;
130     }
131   
132     y = mt[mti++];
133 
134     /* Tempering */
135     y ^= (y >> 11);
136     y ^= (y << 7) & 0x9d2c5680UL;
137     y ^= (y << 15) & 0xefc60000UL;
138     y ^= (y >> 18);
139 
140     return y;
141 }
double genrand_real1 (void)
Definition at line 150 of file MT.cpp.
References genrand_int32().
151 {
152     return genrand_int32()*(1.0/4294967295.0); 
153     /* divided by 2^32-1 */ 
154 }
double genrand_real2 (void)
Definition at line 157 of file MT.cpp.
References genrand_int32().
Referenced by drand().
158 {
159     return genrand_int32()*(1.0/4294967296.0); 
160     /* divided by 2^32 */
161 }
double genrand_real3 (void)
Definition at line 164 of file MT.cpp.
References genrand_int32().
165 {
166     return (((double)genrand_int32()) + 0.5)*(1.0/4294967296.0); 
167     /* divided by 2^32 */
168 }
double genrand_res53 (void)
Definition at line 171 of file MT.cpp.
References genrand_int32().
172 { 
173     unsigned long a=genrand_int32()>>5, b=genrand_int32()>>6; 
174     return(a*67108864.0+b)*(1.0/9007199254740992.0); 
175 } 
void init_by_array (unsigned long init_key[], int key_length)
Definition at line 80 of file MT.cpp.
References init_genrand(), and N.
81 {
82     int i, j, k;
83     init_genrand(19650218UL);
84     i=1; j=0;
85     k = (N>key_length ? N : key_length);
86     for (; k; k--) {
87         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1664525UL))
88           + init_key[j] + j; /* non linear */
89         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
90         i++; j++;
91         if (i>=N) { mt[0] = mt[N-1]; i=1; }
92         if (j>=key_length) j=0;
93     }
94     for (k=N-1; k; k--) {
95         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1566083941UL))
96           - i; /* non linear */
97         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
98         i++;
99         if (i>=N) { mt[0] = mt[N-1]; i=1; }
100     }
101 
102     mt[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */ 
103 }
void init_genrand (unsigned long s)
Definition at line 61 of file MT.cpp.
References N.
Referenced by genrand_int32(), init_by_array(), and setSeed().
62 {
63     mt[0]= s & 0xffffffffUL;
64     for (mti=1; mti<N; mti++) {
65         mt[mti] = 
66             (1812433253UL * (mt[mti-1] ^ (mt[mti-1] >> 30)) + mti); 
67         /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
68         /* In the previous versions, MSBs of the seed affect   */
69         /* only MSBs of the array mt[].                        */
70         /* 2002/01/09 modified by Makoto Matsumoto             */
71         mt[mti] &= 0xffffffffUL;
72         /* for >32 bit machines */
73     }
74 }