bisection.hpp File Reference
Header file for bisection.cpp.
#include `eda.hpp`
Functions
void bisection (Parameters *params, AveragePopulationStatistics *avg_stats)
Bisection method for determining optimal population size.
int do_runs (Parameters *params, AveragePopulationStatistics *avg_stats, int quiet=1)
Run a number of successful runs, terminate on a failure.
void print_bisection_summary (FILE *f, AveragePopulationStatistics *stats)
Print summary of a set of runs (represented by average statistics).
Detailed Description
Header file for bisection.cpp.
Definition in file bisection.hpp.
Function Documentation
void bisection (Parameters * params, AveragePopulationStatistics * avg_stats)
Bisection method for determining optimal population size.
Definition at line 15 of file bisection.cpp.
References do_runs(), AveragePopulationStatistics::population_size, Parameters::population_size, Parameters::quiet_mode, separator(), and Parameters::verbose_mode.
Referenced by main().
16 {
17   AveragePopulationStatistics current_avg_stats;
18   Parameters *current_params = new Parameters;
19   int result;
20   int quiet=params->quiet_mode;
21 
22   params->quiet_mode=1;
23   params->verbose_mode=0;
24 
25   // make the first set of runs
26 
27   *current_params = *params;
28   result=do_runs(current_params,&current_avg_stats,quiet);
29   
30   int minN=0;
31   int maxN=0;
32 
33   if (result)
34     {
35       // if successful, try to halve population size until failure
36 
37       *avg_stats=current_avg_stats;
38 
39       while (result)
40         {
41           current_params->population_size/=2;
42           result=do_runs(current_params,&current_avg_stats,quiet);
43 
44           if (result)
45             *avg_stats=current_avg_stats;
46         };
47       
48       // set initial population size bounds
49 
50       minN=current_params->population_size;
51       maxN=minN*2;
52     }
53   else
54     {
55       // if failure, double population size until success
56 
57       while (!result)
58         {
59           current_params->population_size*=2;
60           result=do_runs(current_params,&current_avg_stats,quiet);
61 
62           if (result)
63             *avg_stats=current_avg_stats;
64         };
65       
66       // set initial population size bounds
67 
68       maxN=current_params->population_size;
69       minN=maxN/2;
70     }
71 
72   // perform bisection until interval width is at most 5% of the
73   // lower bound
74 
75   while ((((double)maxN-minN)/minN)>0.05)
76     {
77       // try to make a set of runs in the middle of the interval
78 
79       current_params->population_size=(minN+maxN)/2;
80       result=do_runs(current_params,&current_avg_stats,quiet);
81 
82       if (result)
83         *avg_stats=current_avg_stats;
84 
85       // success goes halves the interval downwards, failure upwards
86 
87       if (result)
88         maxN=current_params->population_size;
89       else
90         minN=current_params->population_size;
91     }
92 
93   if (quiet==0)
94     {
95       printf("Finished bisection with N=%u\n",avg_stats->population_size);
96       separator(stdout);
97     };
98 
99   delete current_params;
100 }
int do_runs (Parameters * params, AveragePopulationStatistics * avg_stats, int quiet = 1)
Run a number of successful runs, terminate on a failure.
Definition at line 107 of file bisection.cpp.
References average_population_statistics(), Parameters::num_bisection_runs, one_run(), and Parameters::population_size.
Referenced by bisection().
108 {
109   PopulationStatistics *stats = new PopulationStatistics[params->num_bisection_runs];
110   int run;
111   int failed=0;
112   
113   for (run=0; (run<params->num_bisection_runs)&&(!failed); run++)
114     {
115       int result=one_run(params,&stats[run]);
116       failed=!result;
117     };
118   
119   if (quiet==0)
120     printf("bisection -> %2u / %2u successes with N=%u\n",
121            run,params->num_bisection_runs,params->population_size);
122   
123   average_population_statistics(avg_stats,stats,params->num_bisection_runs);
124 
125   delete[] stats;
126 
127   if (failed)
128     return 0;
129   else
130     return 1;
131 }
void print_bisection_summary (FILE * f, AveragePopulationStatistics * stats)
Print summary of a set of runs (represented by average statistics).
Definition at line 138 of file bisection.cpp.
References AveragePopulationStatistics::avg_maxF, AveragePopulationStatistics::avg_num_evals, AveragePopulationStatistics::num_runs, and AveragePopulationStatistics::population_size.
Referenced by main().
139 {
140   fprintf(f,"Bisection summary output:\n");
141   fprintf(f,"   num_runs        = %u\n",stats->num_runs);
142   fprintf(f,"   avg_best_found  = %f\n",stats->avg_maxF);
143   fprintf(f,"   avg_num_evals   = %f\n",stats->avg_num_evals);
144   fprintf(f,"   pop_size        = %u\n",stats->population_size);
145 }