Status Class Reference
Text-mode status bar used in verbose mode in learning algorithms.
#include <status.hpp>
Public Member Functions
Status (int n=55)
void update (double p)
~Status ()
void reset ()
Detailed Description
Text-mode status bar used in verbose mode in learning algorithms.
Definition at line 8 of file status.hpp.
Constructor & Destructor Documentation
Status::Status (int n = 55)
Definition at line 10 of file status.cpp.
11 {
12   last=-1;
13   this->n=n;
14 }
Status::~Status ()
Definition at line 16 of file status.cpp.
17 {
18 }
Member Function Documentation
void Status::reset ()
Definition at line 44 of file status.cpp.
Referenced by TreeModel::learnStructure().
45 {
46   last=-1;
47 }
void Status::update (double p)
Definition at line 20 of file status.cpp.
Referenced by TreeModel::learnProbabilities(), and TreeModel::learnStructure().
21 {
22   int i,k;
23 
24   k=(int)((double)p*n);
25 
26   if (last!=k)
27     {
28       if (last>=0)
29         for (i=0; i<n+2; i++)
30           printf("\b");
31       
32       printf("[");
33       for (i=0; i<k; i++)
34         printf("=");
35       for (i=n-k; i>0; i--)
36         printf("-");
37       printf("]");
38       fflush(stdout);
39       
40       last=k;
41     };
42 }
The documentation for this class was generated from the following files:
status.hpp
status.cpp