eda.cpp File Reference
EDA-specific functions (except for the model-related ones).
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include `eda.hpp`
#include `random.hpp`
#include `obj-function.hpp`
#include `stats.hpp`
#include `tree-model.hpp`
Typedefs
typedef int ReplacementMethod (int **x, int **y, int n, int N, double *fx, double *fy)
Functions
int generate_population (int **x, int n, int N, int *num_vals=NULL)
Generate a random population of individuals (uniform distribution).
int generate_BB_population (int **x, int n, int N, int k)
Generate a poulation full of blocks of 0s and 1s. Only for debugging.
int ** allocate_population (int n, int N)
Allocate memory for a new population of specified parameters.
void free_population (int **x, int n, int N)
Free memory occupied by a population of specified parameters.
int evaluate_population (int **x, double *f, int n, int N, long &num_evals)
Evaluate a population using the user-specified objective function.
int tournament_selection (int **y, int **x, double *f, int n, int N, int k)
Tournament selection with replacement (k-ary tournaments).
void print_population (FILE *f, int **x, int n, int N)
Print the population to the specified file.
int restricted_tournament_replacement (int **x, int **y, int n, int N, double *fx, double *fy)
Restricted tournament replacement (Harik, 1995) for niching.
int full_replacement (int **x, int **y, int n, int N, double *fx, double *fy)
Replace the entire old population with the new population.
int individual_distance (int *x, int *y, int n)
Compute a distance between two individuals (number of non-matching chars).
int one_run (Parameters *params, PopulationStatistics *stats)
Execute one run of a decision-tree EDA with the specified parameters.
int variation (int **sampled_population, int **selected_population, Parameters *params, int *num_vals)
Variation operator of the decision-tree EDA (learns and samples model).
void print_status (int t, PopulationStatistics *stats)
Print the status of the algorithm.
void separator (FILE *f, int type)
Print a sequence of dashes to separate text output.
void print_summary (PopulationStatistics *stats)
Print summary of a run.
Detailed Description
EDA-specific functions (except for the model-related ones).
Definition in file eda.cpp.
Typedef Documentation
typedef int ReplacementMethod(int **x, int **y, int n, int N, double *fx, double *fy)
Definition at line 19 of file eda.cpp.
Function Documentation
int** allocate_population (int n, int N)
Allocate memory for a new population of specified parameters.
Definition at line 84 of file eda.cpp.
Referenced by one_run().
85 {
86   int i;
87   int **x;
88 
89   // allocate a population as a 2-dimensional int-array
90 
91   x=new int*[N];
92   for (i=0; i<N; i++)
93     x[i]=new int[n];
94 
95   // return the allocated array
96 
97   return x;
98 }
int evaluate_population (int ** x, double * f, int n, int N, long & num_evals)
Evaluate a population using the user-specified objective function.
Definition at line 122 of file eda.cpp.
References objective_function().
Referenced by one_run().
123 {
124   // evaluate all individuals, one by one
125 
126   for (int i=0; i<N; i++)
127     f[i]=objective_function(x[i],n);
128 
129   // increase the number of evaluations
130 
131   num_evals+=N;
132 
133   // return the number of evaluated individuals
134 
135   return N;
136 }
void free_population (int ** x, int n, int N)
Free memory occupied by a population of specified parameters.
Definition at line 105 of file eda.cpp.
Referenced by one_run().
106 {
107   int i;
108 
109   // free memory used by the population
110 
111   for (i=0; i<N; i++)
112     delete[] x[i];
113 
114   delete[] x;
115 }
int full_replacement (int ** x, int ** y, int n, int N, double * fx, double * fy)
Replace the entire old population with the new population.
Definition at line 243 of file eda.cpp.
Referenced by one_run().
244 {
245   int i;
246 
247   // just replace entire old population with the new guys
248 
249   for (i=0; i<N; i++)
250     {
251       memcpy(x[i],y[i],sizeof(x[i][0])*n);
252       fx[i]=fy[i];
253     }
254 
255   // return the number of processed new individuals
256 
257   return N;
258 }
int generate_BB_population (int ** x, int n, int N, int k)
Generate a poulation full of blocks of 0s and 1s. Only for debugging.
Definition at line 57 of file eda.cpp.
References drand().
58 {
59   int i,j,l;
60 
61   // generate a population full of 000..0 and 111..1 building blocks
62   // (used for testing the model building procedure, unnecessary for
63   // practical applications)
64 
65   for (i=0; i<N; i++)
66     for (j=0; j<n;)
67       {
68         int val=(drand()<0.5)? 0:1;
69         
70         for (l=0; l<k; l++)
71           x[i][j++]=val;
72     };
73 
74   // return the number of generated individuals
75 
76   return N;
77 }
int generate_population (int ** x, int n, int N, int * num_vals = NULL)
Generate a random population of individuals (uniform distribution).
Definition at line 31 of file eda.cpp.
References drand(), and intRand().
Referenced by one_run().
32 {
33   int i,j;
34 
35   // general all variables uniformly randomly
36   // (if the numbers of values is not supplied, assumes binary)
37 
38   if (num_vals==NULL)
39     for (i=0; i<n; i++)
40       for (j=0; j<N; j++)
41         x[j][i]=(drand()<0.5)? 0:1;
42   else
43     for (i=0; i<n; i++)
44       for (j=0; j<N; j++)
45         x[j][i]=intRand(num_vals[i]);
46 
47   // return the number of generated individuals
48   
49   return N;
50 }
int individual_distance (int * x, int * y, int n)
Compute a distance between two individuals (number of non-matching chars).
Definition at line 265 of file eda.cpp.
Referenced by restricted_tournament_replacement().
266 {
267   int i;
268   int d=0;
269 
270   for (i=0; i<n; i++)
271     if (x[i]!=y[i])
272       d++;
273 
274   return d;
275 }
int one_run (Parameters * params, PopulationStatistics * stats)
Execute one run of a decision-tree EDA with the specified parameters.
Definition at line 282 of file eda.cpp.
References allocate_population(), Parameters::bisection, compute_population_statistics(), evaluate_population(), free_population(), full_replacement(), generate_population(), init_population_statistics(), Parameters::max_generations, N, PopulationStatistics::num_evals, Parameters::population_size, print_status(), Parameters::problem_size, Parameters::quiet_mode, Parameters::replacement, restricted_tournament_replacement(), set_num_vals(), PopulationStatistics::success, tournament_selection(), Parameters::tournament_size, variation(), and Parameters::verbose_mode.
Referenced by do_runs(), and main().
283 {
284   int N=params->population_size;
285   int n=params->problem_size;
286   int max_generations=params->max_generations;
287 
288   int **current_population;
289   int **selected_population;
290   int **sampled_population;
291 
292   double *current_f;
293   double *sampled_f;
294 
295   int *num_vals = new int[n];
296 
297   // allocate populations and necessary fitness arrays
298 
299   current_population = allocate_population(n,N);
300   selected_population = allocate_population(n,N);
301   sampled_population = allocate_population(n,N);
302   
303   current_f = new double[N];
304   sampled_f = new double[N];
305 
306   // initialize the replacement method
307 
308   ReplacementMethod *replacement;
309   if (params->replacement==0)
310     replacement=restricted_tournament_replacement;
311   else
312     if (params->replacement==1)
313       replacement=full_replacement;
314     else
315       {
316         printf("ERROR: Unknown replacement method (%u)\n",params->replacement);
317         exit(-2);
318       };
319 
320   // initialize the number of values
321 
322   set_num_vals(num_vals,n);
323 
324   // generate initial population
325 
326   generate_population(current_population,n,N,num_vals);
327 
328   // evaluate initial population
329 
330   evaluate_population(current_population,current_f,n,N,stats->num_evals);
331 
332   // initialize some main-loop variables
333 
334   int done=0;
335   int t=0;
336 
337   // init the statistics and print the initial status information
338 
339   init_population_statistics(stats);
340   compute_population_statistics(current_population,current_f,n,N,num_vals,stats);
341   
342   if (params->quiet_mode==0)
343     print_status(t,stats);
344   else
345     params->verbose_mode=0;
346 
347   // main loop
348 
349   while (!done)
350     {
351       // increment generation counter
352 
353       t++;
354 
355       // selection
356 
357       tournament_selection(selected_population,
358                            current_population,
359                            current_f,
360                            n,
361                            N,
362                            params->tournament_size);
363 
364       // variation
365 
366       variation(sampled_population,selected_population,params,num_vals);
367 
368       // evaluation of new candidates
369       
370       evaluate_population(sampled_population,sampled_f,n,N,stats->num_evals);
371       
372       // replacement
373       
374       replacement(current_population,
375                   sampled_population,
376                   n,
377                   N,
378                   current_f,
379                   sampled_f);
380 
381       // statistics
382 
383       compute_population_statistics(current_population,current_f,n,N,num_vals,stats);
384 
385       // print current status
386 
387       if ((params->quiet_mode==0)&&(params->bisection==0))
388         print_status(t,stats);
389 
390       // should terminate?
391 
392       if ((t>max_generations)||(stats->success==1))
393         done=1;
394     }
395 
396   // free memory
397 
398   delete[] num_vals;
399   delete[] sampled_f;
400   delete[] current_f;
401 
402   free_population(current_population,n,N);
403   free_population(selected_population,n,N);
404   free_population(sampled_population,n,N);
405 
406   // return with success/failure (0/1)
407 
408   return stats->success;
409 }
void print_population (FILE * f, int ** x, int n, int N)
Print the population to the specified file.
Definition at line 175 of file eda.cpp.
References objective_function().
176 {
177   int i,j;
178   
179   for (i=0; i<N; i++)
180     {
181       for (j=0; j<n; j++)
182         fprintf(f,"%u",x[i][j]);
183       fprintf(f,"   %f\n",objective_function(x[i],n));
184     };
185 }
void print_status (int t, PopulationStatistics * stats)
Print the status of the algorithm.
Definition at line 451 of file eda.cpp.
References PopulationStatistics::avgF, PopulationStatistics::maxF, PopulationStatistics::minF, and separator().
Referenced by one_run().
452 {
453   printf("Generation: %u\n",t);
454   printf("   min:  %f\n",stats->minF);
455   printf("   max:  %f\n",stats->maxF);
456   printf("   mean: %f\n",stats->avgF);
457   separator(stdout);
458 }
void print_summary (PopulationStatistics * stats)
Print summary of a run.
Definition at line 478 of file eda.cpp.
References PopulationStatistics::maxF, PopulationStatistics::num_evals, PopulationStatistics::population_size, PopulationStatistics::problem_size, and PopulationStatistics::success.
Referenced by main().
479 {
480   printf("Summary:\n");
481   printf("   status       = %s\n",(stats->success)? "success":"failure");
482   printf("   best_found   = %f\n",stats->maxF);
483   printf("   num_evals    = %lu\n",stats->num_evals);
484   printf("   pop_size     = %u\n",stats->population_size);
485   printf("   problem_size = %u\n",stats->problem_size);
486 }
int restricted_tournament_replacement (int ** x, int ** y, int n, int N, double * fx, double * fy)
Restricted tournament replacement (Harik, 1995) for niching.
Definition at line 192 of file eda.cpp.
References individual_distance(), and intRand().
Referenced by one_run().
193 {
194   int i,j;
195 
196   // use default value for window size
197 
198   int windowSize=(n<N/20)? n:(N/20);
199 
200   // for every individual, do the same
201 
202   for (i=0; i<N; i++)
203     {
204       // select a random subset from the original population (window) and 
205       // find the most similar guy to the new individual in this window
206       // (string Hamming distance)
207 
208       int pick=intRand(N);
209       int dist=individual_distance(x[i],y[pick],n);
210 
211       for (j=1; j<windowSize; j++)
212         {
213           int pick2=intRand(N);
214           int dist2=individual_distance(x[i],y[pick2],n);
215 
216           if (dist2<dist)
217             {
218               pick=pick2;
219               dist=dist2;
220             }
221         }
222 
223       // if the most similar guy from the window is better than the new guy,
224       // the new guy replaces it
225 
226       if (fx[i]<fy[pick])
227         {
228           memcpy(x[i],y[pick],sizeof(x[i][0])*n);
229           fx[i]=fy[pick];
230         }
231     }
232 
233   // return the number of processed new individuals
234 
235   return N;
236 }
void separator (FILE * f, int type)
Print a sequence of dashes to separate text output.
Definition at line 465 of file eda.cpp.
Referenced by bisection(), print_parameters(), print_status(), and variation().
466 {
467   if (type==0)
468     fprintf(f,"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
469   else
470     fprintf(f,"---------------------------------------------------------------------------\n");
471 }
int tournament_selection (int ** y, int ** x, double * f, int n, int N, int k)
Tournament selection with replacement (k-ary tournaments).
Definition at line 143 of file eda.cpp.
References intRand().
Referenced by one_run().
144 {
145   int i,j;
146 
147   for (i=0; i<N; i++)
148     {
149       // select a winner of k tournaments (with replacement)
150 
151       int winner=intRand(N);
152       for (j=1; j<k; j++)
153         {
154           int l=intRand(N);
155           if (f[l]>f[winner])
156             winner=l;
157         };
158 
159       // the winner takes the next spot in the selected population
160 
161       for (int ii=0; ii<n; ii++)
162         y[i][ii]=x[winner][ii];
163     };
164 
165   // return the number of selected individuals
166 
167   return N;
168 }
int variation (int ** sampled_population, int ** selected_population, Parameters * params, int * num_vals)
Variation operator of the decision-tree EDA (learns and samples model).
Definition at line 416 of file eda.cpp.
References TreeModel::learnProbabilities(), TreeModel::learnStructure(), N, Parameters::population_size, Parameters::problem_size, TreeModel::sampleModel(), separator(), and Parameters::verbose_mode.
Referenced by one_run().
417 {
418   int N=params->population_size;
419   int n=params->problem_size;
420   int loud=params->verbose_mode;
421 
422   if (loud)
423     separator(stdout,0);
424 
425   TreeModel *t = new TreeModel(n, num_vals);
426  
427   // learn the model structure and model parameters
428 
429   t->learnStructure(selected_population,N,loud);
430   t->learnProbabilities(selected_population,N,loud);
431 
432   // sample the learned model to generate new candidate solutions
433 
434   t->sampleModel(sampled_population,N);
435 
436   // free memory
437 
438   delete t;
439 
440   // return the number of generated individuals
441 
442   return N;
443 }