heap.hpp File Reference
Header file for heap.cpp.
Defines
#define HEAP_MINUS_INFINITY -1
Functions
int max_heapify (double *x, int i, int n, int *index, int *rev_index)
Run max-heapify on a specified element of a heap (push down).
int build_max_heap (int *a, int *b, double *x, int n, int *index, int *rev_index)
Build a max-heap for a given array.
int float_up_max_heap (double *x, int i, int n, int *index, int *rev_index)
Float up an element up the heap (after increasing its value).
int increase_key_max_heap (double *x, int i, double val, int n, int *index, int *rev_index)
Increase a given key in the heap.
int pop_max_heap (double *x, int &n, int *index, int *rev_index)
Pop the maximum (includes the removal of maximum).
void print_max_heap (double *x, int n, int *index, int *rev_index)
Print the max heap (used mostly for debugging).
int check_max_heap (double *x, int n, int *index, int *rev_index)
Check the max heap for errors (used mostly in debugging).
Detailed Description
Header file for heap.cpp.
Definition in file heap.hpp.
Define Documentation
#define HEAP_MINUS_INFINITY -1
Definition at line 9 of file heap.hpp.
Referenced by TreeModel::learnStructure().
Function Documentation
int build_max_heap (int * a, int * b, double * x, int n, int * index, int * rev_index)
Build a max-heap for a given array.
Definition at line 19 of file heap.cpp.
References max_heapify().
Referenced by TreeModel::learnStructure().
20 {
21   // builds a max-heap by max-heapifying all nodes with some children
22 
23   for (int i=(n>>1)-1; i>=0; i--)
24     max_heapify(x,i,n,index,rev_index);
25 
26   // get back
27 
28   return n;
29 };
int check_max_heap (double * x, int n, int * index, int * rev_index)
Check the max heap for errors (used mostly in debugging).
Definition at line 156 of file heap.cpp.
157 {
158   int ok=1;
159 
160   for (int i=0; (i<n)&&(ok); i++)
161     {
162       if (i*2+1<n)
163         if (x[index[i]]<x[index[2*i+1]])
164           ok=0;
165 
166       if (i*2+2<n)
167         if (x[index[i]]<x[index[2*i+2]])
168           ok=0;
169     };
170 
171   if (ok==0)
172     printf("not OK\n");
173   else
174     printf("OK\n");
175 
176   return ok;
177 }
int float_up_max_heap (double * x, int i, int n, int * index, int * rev_index)
Float up an element up the heap (after increasing its value).
Definition at line 94 of file heap.cpp.
References parent_index.
Referenced by increase_key_max_heap().
95 {
96   double this_x=x[index[i]];
97   int old_ii=index[i];
98 
99   int parent_idx=parent_index(i);
100 
101   while ((i>0)&&(this_x>x[index[parent_idx]]))
102     {
103       index[i]=index[parent_idx];
104       rev_index[index[i]]=i;
105       i=parent_idx;
106       if (i>0)
107         parent_idx=parent_index(i);
108     };
109 
110   index[i]=old_ii;
111   rev_index[index[i]]=i;
112 
113   return i;
114 };
int increase_key_max_heap (double * x, int i, double val, int n, int * index, int * rev_index)
Increase a given key in the heap.
Definition at line 83 of file heap.cpp.
References float_up_max_heap().
Referenced by TreeModel::learnStructure().
84 {
85   x[i]=val;
86   return float_up_max_heap(x,rev_index[i],n,index,rev_index);
87 };
int max_heapify (double * x, int i, int n, int * index, int * rev_index)
Run max-heapify on a specified element of a heap (push down).
Definition at line 36 of file heap.cpp.
References left_child_index.
Referenced by build_max_heap(), and pop_max_heap().
37 {
38   double this_x=x[index[i]];
39   int old_ii=index[i];
40 
41   int done=0;
42   do {
43     int c1=left_child_index(i);
44     int c2=c1+1;
45 
46     int ic1=index[c1];
47     
48     if (c2<n)
49       {
50         int ic2=index[c2];
51         
52         if (x[ic1]<x[ic2])
53           {
54             ic1=ic2;
55             c1=c2;
56           };
57       };
58     
59     if (x[ic1]>this_x)
60       {
61         index[i]=index[c1];
62         rev_index[index[i]]=i;
63         i=c1;
64         if (left_child_index(i)>=n)
65           done=1;
66       }
67     else
68       done=1;
69     
70   } while (!done);
71   
72   index[i]=old_ii;
73   rev_index[index[i]]=i;
74 
75   return i;
76 };
int pop_max_heap (double * x, int & n, int * index, int * rev_index)
Pop the maximum (includes the removal of maximum).
Definition at line 121 of file heap.cpp.
References max_heapify().
Referenced by TreeModel::learnStructure().
122 {
123   n--;
124   int val=index[0];
125 
126   index[0]=index[n];
127   rev_index[index[n]]=0;
128   max_heapify(x,0,n,index,rev_index);
129 
130   return val;
131 }
void print_max_heap (double * x, int n, int * index, int * rev_index)
Print the max heap (used mostly for debugging).
Definition at line 138 of file heap.cpp.
139 {
140   for (int i=0; i<n; i++)
141     {
142       printf("x[%u] = %5.3f (",i,x[index[i]]);
143       if (i*2+1<n)
144         printf("%5.3f ",x[index[2*i+1]]);
145       if (i*2+2<n)
146         printf("%5.3f ",x[index[2*i+2]]);
147       printf(")\n");
148     };
149 }