obj-function.hpp File Reference
Header file for obj-function.cpp.
Functions
double objective_function (int *x, int n)
The example included by default is a simple onemax problem, which is defined as the sum of all characters in a string (usually binary but it can really be used with any alphabet represented by integers like here).
void set_num_vals (int *num_vals, int n)
Each string position i has values from 0 to num_values[i]-1.
int is_optimal (int *x, int n, int *num_vals)
Verify whether the given solution is the global optimum.
Detailed Description
Header file for obj-function.cpp.
Definition in file obj-function.hpp.
Function Documentation
int is_optimal (int * x, int n, int * num_vals)
Verify whether the given solution is the global optimum.
If there is no such function, just return 0 by default. The default function works for the default objective function, that is, onemax.
Parameters:
x input string (candidate solution)
n string length
num_vals array of the numbers of values for all string positions
Returns: 0 if the solution is non-optimal, something else if the solution is optimal
Definition at line 117 of file obj-function.cpp.
118 {
119   int ok=1;
120 
121   for (int i=0; (i<n)&&(ok); i++)
122     if (x[i]!=num_vals[i]-1)
123       ok=0;
124 
125   return ok;
126 };
double objective_function (int * x, int n)
The example included by default is a simple onemax problem, which is defined as the sum of all characters in a string (usually binary but it can really be used with any alphabet represented by integers like here).
The objective function is coupled with the function that specifies the number of values of all string positions, set_num_vals(int *, int). Both these functions can be found in obj-function.cpp.
Parameters:
x input string (candidate solution)
n string length
Returns: Value of the objective function for the given candidate solution.
Definition at line 36 of file obj-function.cpp.
Referenced by evaluate_population(), and print_population().
37 {
38   int val=0;
39 
40   // compute the sum of all values in the given string
41   // (works also for non-binary representations)
42 
43   for (int i=0; i<n; i++)
44     val+=x[i];
45 
46   // return the final value
47   
48   return val;
49 }
void set_num_vals (int * num_vals, int n)
Each string position i has values from 0 to num_values[i]-1.
By default, the code makes all string positions ternary (values 0 to 2) but alternative assignments can be used.
Parameters:
num_vals array to store the numbers of values for all string positions
n string length
Returns: No return value.
Definition at line 80 of file obj-function.cpp.
Referenced by one_run().
81 {
82   // set the number of values for each string position (variable),
83   // use 2 for binary, 3 or higher for higher candinality alphabets
84 
85   for (int i=0; i<n; i++)
86     num_vals[i]=3;
87 }