parse-input.hpp File Reference
Header file for parse-input.cpp.
#include <stdio.h>
#include `eda.hpp`
Functions
void parse_input_file (FILE *f, Parameters *params)
Parse the input file and store the results in a structure Parameters.
void param_help ()
Print a short description of parameters.
int get_new_identifier (FILE *f, char *s)
Get a new identifier from the file and scan until after next '='.
int get_int_value (FILE *f, int &val)
Read an integer value from a file.
int print_parameters (Parameters *params)
Print the parameters to stdout.
Detailed Description
Header file for parse-input.cpp.
Definition in file parse-input.hpp.
Function Documentation
int get_int_value (FILE * f, int & val)
Read an integer value from a file.
Definition at line 166 of file parse-input.cpp.
References MAX_LINE_WIDTH.
Referenced by parse_input_file().
167 {
168   char line[MAX_LINE_WIDTH];
169   fgets(line,MAX_LINE_WIDTH,f);
170   sscanf(line,"%u",&val);
171 
172   return 1;
173 }
int get_new_identifier (FILE * f, char * s)
Get a new identifier from the file and scan until after next '='.
Definition at line 105 of file parse-input.cpp.
Referenced by parse_input_file().
106 {
107   char c=0;
108   int n=0;
109   int done=0;
110 
111   while ((!feof(f))&&(!done))
112     {
113       c=fgetc(f);
114       if (((c>='a')&&(c<='z'))||
115           ((c>='A')&&(c<='Z'))||
116           (c=='_'))
117         done=1;
118     }
119 
120   if (done)
121     {
122       s[0]=c;
123       n=1;
124       done=0;
125       while ((!feof(f))&&(!done)) 
126         {
127           c=fgetc(f);
128           if (((c>='a')&&(c<='z'))||
129               ((c>='A')&&(c<='Z'))||
130               (c=='_'))
131             s[n++]=c;
132           else 
133             done=1;
134         };
135       s[n]='\0';
136 
137       if (c=='=')
138         done=1;
139       else
140         done=0;
141 
142       while ((!feof(f))&&(!done))
143         {
144           c=fgetc(f);
145           if (c=='=')
146             done=1;
147         };
148       
149       if (!done)
150         {
151           printf("Expected '=' after identifier %s\n",s);
152           exit(-1);
153         }
154 
155       return 1;
156     }
157 
158   return 0;
159 }
void param_help ()
Print a short description of parameters.
Definition at line 83 of file parse-input.cpp.
Referenced by main().
84 {
85   printf("List of parameters for input file (you can specify any subset):\n\n");
86 
87   printf("  -> Population size:\n      population_size = <number>\n\n");
88   printf("  -> Problem size (number of characters):\n      problem_size = <number>\n\n");
89   printf("  -> Maximum number of generations:\n      max_generations = <number>\n\n");
90   printf("  -> Replacement (0=restricted tournament repl., 1=full repl.):\n      replacement = <number>\n\n");
91   printf("  -> Tournament size for tournament selection:\n      tournament_size = <number>\n\n");
92   printf("  -> Use bisection to optimize the population size:\n      bisection = <number>\n\n");
93   printf("  -> Number of successful runs for optimal population sizing:\n      num_runs=<number>\n\n");
94   printf("  -> Quiet mode (prints only the end-of-the-run summary):\n      quiet_mode = <number>\n\n");
95   printf("  -> Verbose mode (do not use with redirected output):\n      verbose_mode = <number>\n\n");
96   printf("  -> Random seed:\n      random_seed = <number>\n\n");
97   printf("See example_input, example_input_bisection, and example_input_big for example input files\n");
98 }
void parse_input_file (FILE * f, Parameters * params)
Parse the input file and store the results in a structure Parameters.
See also: Example input parameter file: example_input
Definition at line 23 of file parse-input.cpp.
References Parameters::bisection, get_int_value(), get_new_identifier(), Parameters::max_generations, MAX_LINE_WIDTH, Parameters::num_bisection_runs, Parameters::population_size, Parameters::problem_size, Parameters::quiet_mode, Parameters::replacement, setSeed(), Parameters::tournament_size, and Parameters::verbose_mode.
Referenced by main().
24 {
25   if (f==NULL)
26     return;
27 
28   char id[MAX_LINE_WIDTH];
29 
30   int seed_set=0;
31   while (get_new_identifier(f,id))
32     {
33       if (strcmp(id,"population_size")==0)
34         get_int_value(f,params->population_size);
35       else
36       if (strcmp(id,"max_generations")==0)
37         get_int_value(f,params->max_generations);
38       else
39       if (strcmp(id,"problem_size")==0)
40         get_int_value(f,params->problem_size);
41       else
42       if (strcmp(id,"replacement")==0)
43         get_int_value(f,params->replacement);
44       else
45       if (strcmp(id,"tournament_size")==0)
46         get_int_value(f,params->tournament_size);
47       else
48       if (strcmp(id,"bisection")==0)
49         get_int_value(f,params->bisection);
50       else
51       if (strcmp(id,"num_bisection_runs")==0)
52         get_int_value(f,params->num_bisection_runs);
53       else
54       if (strcmp(id,"quiet_mode")==0)
55         get_int_value(f,params->quiet_mode);
56       else
57       if (strcmp(id,"verbose_mode")==0)
58         get_int_value(f,params->verbose_mode);
59       else
60       if (strcmp(id,"random_seed")==0)
61         {
62           int seed;
63           get_int_value(f,seed);
64           setSeed(seed);
65           seed_set=1;
66         }
67       else
68         {
69           printf("%s is an unknown identifier\n",id);
70           exit(-1);
71         };
72     };
73   
74   if (seed_set==0)
75     setSeed(123);
76 }
int print_parameters (Parameters * params)
Print the parameters to stdout.
Definition at line 180 of file parse-input.cpp.
References Parameters::bisection, Parameters::max_generations, Parameters::num_bisection_runs, Parameters::population_size, Parameters::problem_size, Parameters::quiet_mode, Parameters::replacement, separator(), Parameters::tournament_size, and Parameters::verbose_mode.
Referenced by main().
181 {
182   printf("Parameters:\n");
183   printf("  population_size    = %u\n",params->population_size);
184   printf("  problem_size       = %u\n",params->problem_size);
185   printf("  max_generations    = %u\n",params->max_generations);
186   printf("  tournament_size    = %u\n",params->tournament_size);
187   printf("  replacement        = %u\n",params->replacement);
188   printf("  bisection          = %u\n",params->bisection);
189   printf("  num_bisection_runs = %u\n",params->num_bisection_runs);
190   printf("  quiet_mode         = %u\n",params->quiet_mode);
191   printf("  verbose_mode       = %u\n",params->verbose_mode);
192   separator(stdout);
193 
194   return 0;
195 }