random.cpp File Reference
Various random number generator related functions based on the basic generator in MT.cpp.
#include <stdio.h>
#include <math.h>
#include `random.hpp`
#include `MT.hpp`
Functions
double drand ()
int intRand (int max)
long longRand (long max)
char flipCoin ()
unsigned long setSeed (unsigned long newSeed)
double gaussianRandom (double mean, double stddev)
Variables
long _Q = _M/_A
long _R = _M%_A
long _seed = 123
char whichGaussian = 0
Detailed Description
Various random number generator related functions based on the basic generator in MT.cpp.
Definition in file random.cpp.
Function Documentation
double drand ()
Definition at line 31 of file random.cpp.
References genrand_real2().
Referenced by flipCoin(), gaussianRandom(), generate_BB_population(), generate_population(), intRand(), and longRand().
32 {
33 //   long lo,hi,test;
34   
35 //   hi   = _seed / _Q;
36 //   lo   = _seed % _Q;
37 //   test = _A*lo - _R*hi;
38   
39 //   if (test>0)
40 //     _seed = test;
41 //   else
42 //     _seed = test+_M;
43 
44 //   return double(_seed)/_M;
45   return genrand_real2();
46 }
char flipCoin ()
Definition at line 96 of file random.cpp.
References drand().
97 {
98   if (drand()<0.5)
99       return 1;
100   else
101       return 0;
102 };
double gaussianRandom (double mean, double stddev)
Definition at line 139 of file random.cpp.
References drand().
140 {
141    double  q,u,v,x,y;
142 
143    /*  
144       Generate P = (u,v) uniform in rect. enclosing acceptance region 
145       Make sure that any random numbers <= 0 are rejected, since
146       gaussian() requires uniforms > 0, but RandomUniform() delivers >= 0.
147    */
148    do {
149       do { u=drand(); } while (u==0);
150       do { v=drand(); } while (v==0);
151 
152       v = 1.7156 * (v - 0.5);
153 
154       /*  Evaluate the quadratic form */
155       x = u - 0.449871;
156       y = fabs(v) + 0.386595;
157       q = x * x + y * (0.19600 * y - 0.25472 * x);
158 
159       /* Accept P if inside inner ellipse */
160       if (q < 0.27597)
161          break;
162 
163       /*  Reject P if outside outer ellipse, or outside acceptance region */
164     } while ((q > 0.27846) || (v * v > -4.0 * log(u) * u * u));
165 
166     /*  Return ratio of P's coordinates as the normal deviate */
167     return (mean + stddev * v / u);
168 }
int intRand (int max)
Definition at line 60 of file random.cpp.
References drand().
Referenced by generate_population(), TreeModel::learnStructure(), restricted_tournament_replacement(), and tournament_selection().
61 {
62 //   double r=drand();
63 //   printf("r=%f\n",r);
64   return (int) (drand()*max);
65 };
long longRand (long max)
Definition at line 79 of file random.cpp.
References drand().
80 {
81    return (long) ((double) drand()*max);
82 };
unsigned long setSeed (unsigned long newSeed)
Definition at line 116 of file random.cpp.
References init_genrand().
Referenced by parse_input_file().
117 {
118   // set the seed and return the result of the operation
119   
120   init_genrand(newSeed);
121 
122   return newSeed;
123 };
Variable Documentation
long _Q = _M/_A
Definition at line 12 of file random.cpp.
long _R = _M%_A
Definition at line 13 of file random.cpp.
long _seed = 123
Definition at line 14 of file random.cpp.
char whichGaussian = 0
Definition at line 16 of file random.cpp.