stats.cpp File Reference
Functions for computing basic population statistics.
#include `obj-function.hpp`
#include `stats.hpp`
Functions
int compute_population_statistics (int **x, double *f, int n, int N, int *num_vals, PopulationStatistics *stats)
Compute basic population statistics like the maximum, mean, etc.
void init_population_statistics (PopulationStatistics *stats)
Initialize the population statistics structure.
int average_population_statistics (AveragePopulationStatistics *avg, PopulationStatistics *stats, int num_runs)
Compute averages of population statistics over multiple runs.
Detailed Description
Functions for computing basic population statistics.
Definition in file stats.cpp.
Function Documentation
int average_population_statistics (AveragePopulationStatistics * avg, PopulationStatistics * stats, int num_runs)
Compute averages of population statistics over multiple runs.
Definition at line 74 of file stats.cpp.
References AveragePopulationStatistics::avg_avgF, AveragePopulationStatistics::avg_maxF, AveragePopulationStatistics::avg_minF, AveragePopulationStatistics::avg_num_evals, PopulationStatistics::avgF, AveragePopulationStatistics::max_maxF, PopulationStatistics::maxF, AveragePopulationStatistics::min_minF, PopulationStatistics::minF, PopulationStatistics::num_evals, AveragePopulationStatistics::num_runs, AveragePopulationStatistics::population_size, PopulationStatistics::population_size, AveragePopulationStatistics::problem_size, and PopulationStatistics::problem_size.
Referenced by do_runs().
75 {
76   // initialize the average stats
77 
78   avg->avg_minF=stats[0].minF;
79   avg->avg_maxF=stats[0].maxF;
80   avg->avg_avgF=stats[0].avgF;
81   avg->avg_num_evals=stats[0].num_evals;
82 
83   avg->min_minF=stats[0].minF;
84   avg->max_maxF=stats[0].maxF;
85 
86   avg->population_size=stats[0].population_size;
87   avg->problem_size=stats[0].problem_size;
88   avg->num_runs=num_runs;
89 
90   // do the homework
91 
92   for (int run=1; run<num_runs; run++)
93     {
94       avg->avg_minF+=stats[run].minF;
95       avg->avg_maxF+=stats[run].maxF;
96       avg->avg_avgF+=stats[run].avgF;
97       avg->avg_num_evals+=stats[run].num_evals;
98 
99       if (stats[run].minF<avg->min_minF)
100         avg->min_minF=stats[run].minF;
101 
102       if (stats[run].maxF>avg->max_maxF)
103         avg->max_maxF=stats[run].maxF;
104     }
105 
106   avg->avg_minF/=num_runs;
107   avg->avg_maxF/=num_runs;
108   avg->avg_avgF/=num_runs; 
109   avg->avg_num_evals/=num_runs;
110 
111   // return the number of processed runs
112 
113   return num_runs;
114 }
int compute_population_statistics (int ** x, double * f, int n, int N, int * num_vals, PopulationStatistics * stats)
Compute basic population statistics like the maximum, mean, etc.
Definition at line 15 of file stats.cpp.
References PopulationStatistics::avgF, PopulationStatistics::idx_maxF, PopulationStatistics::idx_minF, PopulationStatistics::maxF, PopulationStatistics::minF, PopulationStatistics::population_size, and PopulationStatistics::problem_size.
Referenced by one_run().
16 {
17   // store population size and problem size
18 
19   stats->population_size=N;
20   stats->problem_size=n;
21 
22   // compute basic fitness statistics
23 
24   stats->idx_minF = stats->idx_maxF = 0;
25   stats->minF = stats->maxF = stats->avgF = f[0];
26 
27   for (int i=1; i<N; i++)
28     {
29       stats->avgF+=f[i];
30 
31       if (f[i]>stats->maxF)
32         {
33           stats->maxF=f[i];
34           stats->idx_maxF=i;
35         }
36       else
37         if (f[i]<stats->minF)
38           {
39             stats->minF=f[i];
40             stats->idx_minF=i;
41           }
42     }
43 
44   stats->avgF/=N;
45 
46   // check whether we found the optimum
47 
48   if (is_optimal(x[stats->idx_maxF],n,num_vals))
49     stats->success=1;
50 
51   // get back
52 
53   return 0;
54 }
void init_population_statistics (PopulationStatistics * stats)
Initialize the population statistics structure.
Definition at line 61 of file stats.cpp.
References PopulationStatistics::avgF, PopulationStatistics::idx_maxF, PopulationStatistics::idx_minF, PopulationStatistics::maxF, PopulationStatistics::minF, PopulationStatistics::num_evals, and PopulationStatistics::success.
Referenced by one_run().
62 {
63   stats->num_evals=0;
64   stats->minF=stats->maxF=stats->avgF=0;
65   stats->idx_minF=stats->idx_maxF=-1;
66   stats->success=0;
67 }